"""Initial migration

Revision ID: 04d2a6bb3420
Revises: 
Create Date: 2026-01-12 15:54:49.679787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d2a6bb3420'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False, comment="User's preferred language: en, ru, et"),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment="User's timezone (e.g., 'Europe/Tallinn')"),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False, comment='Whether user completed initial onboarding'),
    sa.Column('target_bedtime', sa.Time(), nullable=True, comment='Target time to go to bed (e.g., 22:00)'),
    sa.Column('target_wake_time', sa.Time(), nullable=True, comment='Target time to wake up (e.g., 06:00)'),
    sa.Column('target_sleep_hours', sa.Integer(), nullable=True, comment='Target sleep duration in hours (e.g., 8)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(timezone=True), nullable=False, comment='When user started sleeping (UTC)'),
    sa.Column('sleep_end', sa.DateTime(timezone=True), nullable=True, comment='When user woke up (UTC), NULL if still sleeping'),
    sa.Column('duration_hours', sa.Float(), nullable=True, comment='Sleep duration in hours'),
    sa.Column('quality_rating', sa.Float(), nullable=True, comment='Sleep quality rating (1.0 - 10.0)'),
    sa.Column('note', sa.Text(), nullable=True, comment="User's notes about this sleep session"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_sessions_user_id'), 'sleep_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_sessions_user_id'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
